# PROMPT
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

# SOLUTION

require 'pry'

# initialize fib sequence to 1,2 instead of 1,1
fib_sequence = [1, 2]
# generate all values below 4,000,000
until fib_sequence[-1] + fib_sequence[-2] >= 4000000 do
  x = fib_sequence[-2]
  y = fib_sequence[-1]
  b = x + y
  fib_sequence.push(b)
end

# change so that it's only even values
fib_sequence.select! do |fib|
  fib.even?
end

# reduce and return the sum of all the even values

fib_sequence.reduce(0) {|sum, current_term| sum + current_term}
